[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
candid = "0.7.14"
ic-cdk = "0.5.2"
ic-cdk-macros = "0.5.2"
ic-stable-structures = "0.3.0"
serde_cbor = "0.10"
serde = {version = "1.0" }
serde_json = {version = "1.0"}